services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: guilherme_user
      POSTGRES_PASSWORD: guilherme_password
      POSTGRES_DB: todolist
    volumes:
      - guilherme_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: guilherme_api
    restart: always  # <-- Se a API cair, o Docker sobe ela de novo até o banco estar pronto.
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "3018:3000"


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/tarefas"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s  

    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Cada arquivo de log terá no máximo 10MB
        max-file: "3"     # O Docker guarda apenas os últimos 3 arquivos (total 30MB)  

  web:
    build: ./frontend
    container_name: guilherme_web
    ports:
      - "8018:80"
    depends_on:
      api:
        condition: service_healthy

volumes:
  guilherme_data: