services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: guilherme_user
      POSTGRES_PASSWORD: guilherme_password
      POSTGRES_DB: todolist
    volumes:
      - guilherme_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: guilherme_api
    restart: always  # <-- Se a API cair, o Docker sobe ela de novo até o banco estar pronto.
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "3018:3000"

  web:
    build: ./frontend
    container_name: guilherme_web
    ports:
      - "8018:80"
    depends_on:
      - api

volumes:
  guilherme_data: