name: CI - app_simples

on: 
  push:
    branches: [ main ]

jobs:

 build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
 
      - name: Build com Docker Compose
        run: docker compose build
 
      - name: Push com Docker Compose
        run: docker compose push

deploy:
  needs: build
  runs-on: ubunto-latest
  steps:
    -name: Deploy via SSH (Appleboy)
    -uses: appleboy/ssh-action@master
    with:
      host: ${{secrets.SSH_USER }}
      key: ${{ secrets.SSH_KEY }}
      script: |
        # entra na home do usuário
        cd ~
        # se o projeto nao existe, clona. Se existe, pull
        if [ ! -d "guilherme-app" ]; then
          gitclone https://github.com/${{ github.repository }} guilherme-app
        fi
        cd guilherme-app
        git pull originmain
        docker compose pull
        docker compose up -d

